* Org Mode
** Outline and Writing
*** insert heading
    M-Enter will insert a heading in current position
        and the newly heading is same with privious heading
*** promote heading
    M-Left  will promote the heading by one level
*** demote heading 
    M-Right will demote the heading by one level
*** promote entire subtree
    M-Shift-Left will promote an entire subtree
*** demote entire subtree
    M-Shift-Right will demote an entire subtree
** Plain List
*** unordered plain list
   - first subitem
   - second subiten
     + another item
     + some thing else

(- or +) then press M-Enter, org mode will add a (- or +) automatically
*** ordered plain list
   1. this is the first item
   2. this is the second item
   3. hsh
   4. this is the trird item
(1.) then press M-Enter, org mode will add a (2.) automatically
*** add a checkbox
   - [ ] this is fiest checkbox
   - [ ] this is second checkbox
   - [ ] this is third checkbox
   start the line with - [ ], toggle the check box using C-c C-c
** hyper links
*** simple urls
    http://www.baidu.com
*** link to file
    file:/files.txt
** tab
* Gdb usage
** compiling source file to debug            :symbolic:dubugging:information:
   gcc -g test.c -o test
   g++ -g test.cpp -o test

** debug in a gui mode
   gdb -tui
   arrow and page(down/up) key will srcoll the source window
   
   >list test.c:4 will bring up the file test.c on line 4

   >r or >run will run the program
   >r arg1 arg2 will run the program with the arguments

** break point
   >b main        :break at the main function
   >b 5           :break at the 5th line
   >b test.c:5    :break at line 5 of test.c

   >i b           :(info b) get the infomation of the break point

*** disable a break
   >disable 1     :disable the first break
   >clear main    :clear the break "main"


*** stepping
    >n             :move you to the next statement
    >s             :step into a function
    >c             :continue excution
    >[Enter]       :repeat last command you input

*** examing varible
   >disp i               :display the variable i, and display it every time you stop code
   >undisp i             :undisplay
   >info display
   >print i              :one-off display
   >printf "format" i    :format display

** misc stuff
*** backtrace
    >backtrace            :(bt) show current function call stack
*** addtional stepping
    >finish               :exit current excution function and return to the calling function
    >stepi                :step a single assembly instuction
    >advance loc          :coutinue to this temp loc
*** jump to arbitrary section
    >jump 3               :jump to line 3    
*** set variables and values
    >set (i=20)
    >set variable i = 40
*** hardware watch point
    >watch var
     
* Emacs...
** Go back to a previous position:
   exchange-point-and-mark [C-x C-x]

** [Bookmark]
   C-x r m   : set s bookmark
   C-x r l   : list bookmarks
   C-x r b   : jump to bookmark

** [Register]
   C-x r n : store number in register
   C-x r s : store region in register
   C-x r SPC : store point in register
   C-x r + : increment number in register
   C-x r j : jump to register
   C-x r i : insert content of register
   C-x r w : store window configuration in register
   C-x r f : store frameset in register

** [Neotree]
   C-c n : neotree toggle
   C-c c : neotree set directory

** [C-u] universal aguments:
   * C-u a : display aaaa
   * C-u C-u a : display aaaaaaaaaaaaaaaa
   * C-u 10 a : display aaaaaaaaaa
   * M-0 to M-9:
     M-5 a : display aaaaa
   * M-d : kill the word immediatly following point
     M-- M-d : kill the word immediatly before point

** emacs command tempo
   M-- M-d kill the previous word before point
           you just keep your finger on mata key and press - d
	       this combination do not break "tempo"

   C-- M-d do the same thing
           but you have to press C--, then release and press M-d

   Negative argment add directionality to commands
   Digits add repetition or change how a command works

   Example: when a edit a line, i want to change the previous word from low case to upcase
            how can i do IT?

   Solve:
	 M-l : convert following word to lower case
	 M-u : convert following word to upper case
	 M-- M-u : convert previous word to upper case

	 M-c : capitalize the following word
	 C-x C-l : convert region to lower case
	 C-x C-u : convert region to upper case

     C-x C-h : the help doc of the C-x

** Configuring Emacs:
   5.1 [M-x Customize] display the Customize interface and all the group
   [M-x Customize] -> change some config -> save and apply

   5.2 Use Emacs Lisp

   find help in emacs:
   * [Info Manual]
     [M-x info] or [C-h i]

   * [Apropos]
     it shines because you can narrow what you are looking for
     it support regular expression

     [example] find all commands work on word
     [C-h a -word$]

     [M-x apropos] track down both variables, commands and functions
     [M-x apropos-command or C-h a] only command

** movement
   In emacs, the syntax table alone decides the makeup of a word as
   a syntactic unit.

   moving by s-expression:

   Example:
   d = {
     'Hello' : 'world',
     'Foo' : 'bar',
     }

   [C-M-f] move forward by s-expression
   [C-M-b] move backward by s-expression
   [C-M-n] Move forward to the next list
   [C-M-p] move backward to the previous list

   [C-M-u] [C-M-k] move up and kill the balanced expression you were just In

   moving by line:

   This is a test line;
   [C-a] moves point to the begining of the line
   [C-e] moves point to the end of the line
   [M-m] moves point to the first no-white space character of the line

   moving by word:
   [M-f] move forward by word
   [M-b] move backward by word

   word movement is dictated by the major mode you are using

   what is a word?
   when you move the point around the screen, it moves according to the syntax table
   and the general rules governing forward-word and backward-word

   [C-h s] view syntax table of current buffer

   word movement is not symmetri

** special movement
   7.1 move by paragraph
   [M-{] move forward to the end of the paragraph
   [M-}] move backward to the begining of the paragraph

   7.2 move by sentence
   this is a sentence.  This is other sentence.
   [M-a] moving to the begining of a sentence
   [M-e] moving to the end of a sentence

   7.3 move by defun

   int addtwo(int a, int b)
   {
	return a+b;
   }

** Book Mark and Register:
   [C-x r m] set a bookmark
   [C-x r l] list bookmark
   [C-x r b] jump to bookmark

   you can use help memory: book mark is just a kind of rigister
   r could mean register
   
   m : set mark
   l : list mark
   b : browse a mark

   Book mark is permenent, but rigister is transient:
   you can store follwing data into rigister:
   a. window configurations and framesets
   b. points
   c. numbers and text

   use rigster store a rigion and then copy the
   context of this rigion to other place

   A. set mark and move point to store a rigion
   B. C-x r s save the rigion, then input a character to name the rigion
   c. C-x r i insert the rigion, input the character is ok

** Selection and Region
   the boundary of a region is made up of point and the mark
   the region is always defined as the continous block of text
   between the point and the mark.

   tips: use help in Emacs
   [C-h w] command-name
   [C-h k] key-sequence
   [C-h f] function-name
   [C-h f] variable-name

   command of region and mark:
   [C-q] set the mark and toggle the region
   [C-q] [C-q] set the mark and then deactive it
   [C-u] [C-q] jumps to the mark, and repeat calls
               calls go further back the mark ring

   [C-x] [C-x] Exchange the point and the mark
               you can see the point's move

   Selection Compatility Mode:

   9.1 Delete-Selection-Mode:
       input text will delete the selected region
   9.2 Shift-Selection-Mode:
       S+<right> or S+<left> will select the rigion one character by one
   9.3 CUA mode:
       Let you use
       C-z undo
       C-x cut
       C-c copy
       C-v paste
       as a new emacs user, you may use it.
       after some time, get out of it.

** Setting the mark:
   the C-<SPC> set the mark, then move the point to select the region.
   then do some funtion on this region.
   That some curbersome, if you want to make precise selections,
   you better use emacs's dedicated mark command

   [M-h] Mark the next paragraph
   [C-x h] Mark the whole buffer
   [C-M-h] Mark the next defun
   [C-x C-p] Mark the next page
   [M-@] Mark the next word

   emacs useful mark command:
   mark-defun
   mark-end-of-sentence
   mark-page
   mark-paragraph
   mark-sexp
   mark-whole-buffer
   mark-word

** Searching and Indexing
    key binding		Purpose
    C-s			Begins an incremental Searching
    C-r			Begins an backward incremental Searching
    C-M

    Emacs case key binding and command

    key binding	   Purpose
    M-l		   downcase-word
    M-u		   uppercase-word
    M-c		   capitalize-word

    C-x C-l	   downcase-region
    C-x C-u	   uppercase-region

    Searching History (Searching ring)

    M-n	      	   move to next item in searching History
    M-p 	   move to previous item in searching History
    C-M-i	   "TAB"-complete search string against previous searching ring
    C-s C-s 	   Begin Isearch against last search string
    C-r C-r	   Begin backward Isearch against last Searching string

    searching for strings at point:
    C-w	      Add word at point to the searching string
    C-M-y     Add character at point to the searching string
    [just use backspace to delete added word or character]

    M-s C-e   add rest of line to search ring
    C-y	      "yank" from clipboard to search string


    some searching toggle:
    M-s c or [M-c]	Toggles case-sensitivity
    M-s r or [M-r]      Toggles	regular-expression mode
    M-s w    		Toggles word mode
    M-s _		Toggles symbol mode
    M-s <SPC>		Toggles lax whitespace matching

    Each toggle command only affects the current Isearch and will not persist.

** Occur: Print lines matching an expression
    M-s o  	 Occur Mode
    M-s o 	 Activate occur on current search string
    		 inside Isearch

    In occur mode, you can use such useful keys:
    M-n, M-p 	 Go to next and previous occurrence
    <,>	 	 Go to beginning and end of the buffer
    g		 Revert the buffer
    q		 Quit
    e		 Switch to occur edit mode : Why this is a useful command
    C-c C-c	 Exit occur edit mode

    you can use occur to search something, then use "e" swicth
    to occur edit mode, change the searching result, finally
    use C-c C-c save the change.

** Edit: kill and Yank Text
    [key binding]	[Purpose]
    C-d	 		Delete character
    <Backspace>		Delete Previous character
    M-d,C-<backspace>	Kill word
    C-k			Kill rest of line
    M-k			Kill sentence
    C-M-k		Kill s-expression
    C-S-<backspace>	kill current line

    The difference bettween delete and kill:
    deleted text is not retained in your kill ring whereas killed text is.

    digits argument and negative argument:
    C-3 C-d 	    Delete 3 character after current point
    C--	C-d	    Delete 1 character before current point
    M-3 M-d	    Kill 3 words after current point
    C-M-- C-M-k	    Kill s-expression before current point

    clipboard-equivalent commands in Emacs:
    C-w	    	    Kill active region(cut)
    M-w		    Copy to kill ring (copy)
    C-M-w	    Append kill
    C-y		    Yank last kill (paste)
    M-y		    Cycle through kill ring,
    		    replace yanked text

    Tips about emacs Kill:
    A. Consecutive kills append to the kill ring
    B. The kill ring can hold many items
    C. The kill ring is global bettween all the buffers in Emacs
    D. Killing is also deleting
    E. Marking is unnecessary
       M-d is much quick than "C-@ C-w"

** Transposing text:
    [key binding]   [Purpose]
    C-t	 			Transposing characters
    M-t				Transposing words
    C-M-t			Transposing s-expressions
    C-x C-t			Transposing lines
    M-x transpose-paragraphs	transposing paragraphs
    M-x transpose-sentences	Transposing sentences

** emacs as a c/c++ ide
    (use linux kernel source as test project)

** M-s . : isearch-forward-symbol-at-point
    search a word at point

** using register in emacs:
    what we can put in the register?
    A. a piece of text
    B. a rectangle of text
    C. position we want to move back

    each register has its own name, such as 'a' or 'A';
    'a' and 'A' are diffrent

    a rigister can contain one thing at a time

    M-x view-register <RET> r
       Display a description of what register r contains

    18.1 position register

         Record the position of point and the current buffer in register r(point-to-register)
         C-x r <SPC> r

         after the above command, we can view-register:
         Register r contains a buffer position:
         buffer emacs.txt, position 9916

    18.2 text register

         Copy region into register r(copy-to-register)
         C-x r s r
         Insert text from register r(insert-register)
         C-x r i r

         Append region to text in register r
         M-x append-to-register <RET> r
         Prepend region to text in register r
         M-x prepend-to-register <RET> r

** column editing
    1. select a rectangle(region) and delete

    M-x set-mark-command
    Move the point to some position
    M-x kill-rectangle

     4567 8900 1234
     2222 2222 2344
     3334 3333 2222

    2. replace a rectangle(region)

    M-x set-mark-command
    Move the point to some position
    M-x replace-rectangle

    3. yank and paste rectangle(region)

    M-x set-mark-command
    Move the point to some position
    M-x kill-rectangle
    move the point to another position
    M-x yank-rectangle

    4. insert a column of numbers

    M-x set-mark-command
    Move the point to next line begin position
    M-x rectangle-line-numbers
    
    1 hjiang
    2 heng
    3 heng

    5. move a region

    djhksh
    jskldjl
    kjhsdk
** Short cut keystrock...
   M-s s      ---> set-mark-command
   M-s n      ---> neotree-toggle
   C-x space  ---> rectangle-mark-mode
** Org mode...
** remember some position and then go back
   C-x r <SPC> r      (point-to-register)
   C-x r j r          (jump-to-register)
*** Insert a column/row in a table:
    S-M-<right>: insert a column before current cell
    S-M-<down>: insert a row before current row
*** Moving rows/cloumns
    M-<down>: move current row down
    M-<right>: move current column right
* Emacs+Git => Magit
** magit-status : to display information about the current Git repository 
** p,n : Move between sections using ~p~ and ~n~.
   [tab]: expand or collapse the section at point.
   staging:         ~s~ to stage the changes you have made to specific file.
   unstaging:       (~u~) commands operate on the change at point
   commit:          And then of course you want to commit your changes.  Type ~c~.
   common commit:   We want to create a "normal" commit, which is done by typing ~c~ again
   real commit:     Write a message and then type ~C-c C-c~ to actually create the commit.
   push:            ~P~ to bring up the push popup
                    ~p~ to push to a branch with the same name as the local branch onto the
                    remote configured as the push-remote

* unix/linux
** append one file to another file's tail
   cat file1.txt >> file2.txt
** something about using git
*** initialize a empty Git repository :
   git init

   The previous command will init a '.Git' directory in
   current directory. the structure of this directory is
   like:
   -----------------------------------------------------
   HEAD
   config
   description
   hooks/
   info/
   objects/
   refs/
   -----------------------------------------------------
   Tips: config is the only file that we can change

*** git config
   config is done at 3 stages:
   1. system(--system)
   2. user(--global)
   3. project

   Example1:
   git config user.email hjiang@sse.com.cn

   The previous command will append two lines to "config" file:
   [user]
	email = hjiang@sse.com.cn


   Example2:
   git config --global user.name "hjiang"
   git config --global user.ID "0715039"

   the previous commands will add three lines to .gitconfig in $HOME
   [user]
       name = hjiang
       ID = 0715039

*** git arch
   view git in three level
   [level-1] User Working Dir
   [level-2] Stage(index)
   [level-3] Repository

   2-step process:
   lev-1 ---> lev-2 : git add
   lev-2 ---> lev-3 : git commit

   lev-3 ---> lev-2 : git reset --
   lev-2 ---> lev-1 : git checkout --

   1-step process:
   lev1-->lev2-->lev3 : git commit -a
   lev3-->lev2-->lev1 : git checkout HEAD --

   2.4 git updating repository
   git add filename
   git commit -m "some kind of message"

   2.5 git checkout

   a. to the latest version:
      git checkout -- filename

   b. to any previous version:
      git log
      the previous command will get commit infomation:

   commit 34ccee5100c00b2668f9f785c000e8ae75c9d73a
   Author: hjiang <hjiang@sse.com.cn>
   Date:   Mon Nov 6 11:10:53 2017 +0800

       add a line in File1.txt

   commit 25f65bf8abd9190509dbdd19ee97593318fe1c43
   Author: hjiang <hjiang@sse.com.cn>
   Date:   Mon Nov 6 11:02:28 2017 +0800

       First line was written at file1.txt

   commit a11b757a56870313c98e86d476416158f0cd2925
   Author: hjiang <hjiang@sse.com.cn>
   Date:   Mon Nov 6 10:59:00 2017 +0800

       This is a test of git commit
   
** introduce to make file:
   /src : contain source file
          main.cpp, extra.cpp, other.cpp
   /bin : contain dest binary file

   makefile:
   bin/myprogm: src/extra.cpp src/main.cpp src/other.cpp
       g++ $^ -o $@

   then in command line:
   make
   or make -B

** split a text file in to a word list
   tr -s '[[:punct:][:space:]]' '\n' < testfile.txt
** find command
*** find a string in a directory[the directory have multi files]
    grep -rnw '/path/to/somewhere/' -e 'pattern'
*** find a file bigger or smaller than a given size 
    find . -type f -size +6096c [find files bigger than 6096bytes]
   find . -type f -size -6096c [find files smaller than 6096bytes]


          -size n[cwbkMG]
              File uses n units of space, rounding up.  The following suffixes
              can be used:

              `b'    for  512-byte blocks (this is the default if no suffix is
                     used)

              `c'    for bytes

              `w'    for two-byte words

              `k'    for Kilobytes (units of 1024 bytes)

              `M'    for Megabytes (units of 1048576 bytes)

              `G'    for Gigabytes (units of 1073741824 bytes)

              The size does not count  indirect  blocks,  but  it  does  count
              blocks in sparse files that are not actually allocated.  Bear in
              mind that the `%k' and `%b' format specifiers of -printf  handle
              sparse   files  differently.   The  `b'  suffix  always  denotes
              512-byte blocks and never 1 Kilobyte blocks, which is  different
              to  the  behaviour of -ls.  The + and - prefixes signify greater
              than and less than, as usual, but bear in mind that the size  is
              rounded  up to the next unit (so a 1-byte file is not matched by
*** linux 在一个文件夹中的所有文件中查找一个字符串:
  grep -rnw '/path/to/somewhere/' -e 'pattern'
  r: recursive
  n: number of the line
  w: match the whole word

  search the files which have .c or .h extensions:
  grep --include=\*.{c,h} -rnw 'path/to/somewhere' -e 'pattern' 

  exclude searching all the files ending with .o extension:
  grep --exclude=\*.o -rnw 'path/to/somewhere' -e 'pattern' 

  --exclude-dir, --include-dir

*** Search within files
    Search for files only end with .php and look for the string "$test" inside those files:
    
    1. find -exec \;
       find . -name \*.php -type f -exec grep -Hn '$test' {} \;

    2. find -exec \+
       find . -name \*.php -type f -exec grep -Hn '$test' {} \+

    3. find | xargs -n1
       find . -name \*.php -type f -print0 | xargs -0 -n1 grep -Hn '$test'

    4. find | xargs
       find . -name \*.php -type f -print0 | xargs -0 grep -Hn '$test'

** sed command
   essential command: s for substitution
   sed 's/one/ONE' file.txt
   s: substitution command
   /../../ : delemeter
   one : Regular expression Pattern Search Pattern
   ONE : Replacement string

   using & as the matched string:

   extened regular expression:
   echo "123 abc" | sed -r 's/[0-9]+/& &/'
   -r: stand for extented regular expression

   using \1 to keep part of the pattern:
   sed 's/\([a-z]*\).*/\1/' Basic.sh , will keep the first word of this line
   sed 's/\([a-z]*\) \([a-z]*\)/\2 \1/' Basic.sh , will switch two word
   sed 's/\([a-z][a-z]*\) \([a-z][a-z]*\)/\2 \1/' file.txt , ensure a word has least one letter

   sed -r 's/([a-z]+) ([a-z]+)/\2 \1/' file.txt , using extended regular expression
   sed -r 's/([a-z]+) \1/\1/' file.txt , \1 can occur in the pattern regular expression
   sed -nr '/([a-z]+) \1/p' file.txt , will detect duplicated words
   sed -r 's/(.)(.)(.)/\3\2\1/' file.txt, reverse first three cha on a line

   Sed Pattern Flag, specify what happens when a match is found
   sed 's/[^ ]*/(&)/' test.txt, this parenthesis around the first word
   sed 's/[^ ][^ ]*/(&)/g' test.txt, this parenthesis around all the word

   /1, /2 etc. Specifying witch occurrence
   sed -r 's/([a-zA-Z]*) ([a-zA-Z]*)/\1 /' test.txt, keep the first word on line and leave the next
   sed -r 's/([a-zA-Z]*) //1' test.txt, same as privious line
   sed -r 's/[a-zA-Z]* /DELETED /1g' test.txt
   sed 's/[a-zA-Z]* /DELETED /2g' test.txt

   sed -e 's/a/A/' -e 's/b/B' test.txt , multiple command with -e

** history command
     !! : repeat last command
     !ssh : recall last command start with ssh
     history : see the list of excuted command
     !13 : recall command with index is 13

** perl code debug
    h or h h – for help page
    c – to continue down from current execution till the breakpoint otherwise till the subroutine name or line number,
    p – to show the values of variables,
    b – to place the breakpoints,
    L – to see the breakpoints set,
    d – to delete the breakpoints,
    s – to step into the next line execution.
    n – to step over the next line execution, so if next line is subroutine call, it would execute subroutine but not descend into it for inspection.
    source file – to take the debug commands from the file.
    l subname – to see the execution statements available in a subroutine.
    q – to quit from the debugger mode.
** use dd command make usb booter...
   sudo umount /dev/sda
   sudo dd bs=4M if=input_linux.iso of=/dev/sda conv=fdatasync
* passwd
  OA and OutNet:
  Name:hjiang
  Passwd: Jiang0715039

  AST591:198.2.11.1
  AST592:198.2.156.1
  AST593:198.2.56.1
  AST594:198.2.186.1
  DEV03:172.23.1.101

  OA信息管理系统:
  User:hjiang
  Passwd:hjiang

  远程报单数据库地址: 10.112.3.249
  ezstep_jiangheng
  sa
  sa

  CSGW ip and Passwd:
  ip: 198.2.243.1
  user: sg\se001
  passwd: senew001

  EzFT ip and passwd:
  ip: 196.123.132.152 
  user: bpc_opt
  passwd: BPCqdckmm@00

  196.123.134.171
* OpenVms
** EzEI extract 广播数据使用说明：
  0）进入 bin目录，重置环境变量
  . ./setenv 

  1）导出oc二进制数据。 -set后参数表示set号， -tp参数是主题名， -startno表示主题起始号， -endno是结束号， -fipath表示导出二进制文件路径
  ./showall -bcdt -set 109 -tp 1 -startno 1 -endno 100 -fipath ../data/output/109-1.txt

  2、使用showbcdt解析出的可视化数据,  -s为showall导出文件位置， -conf 为配置文件位置， -o为数据文件位置（可显示文件）
  ./showbcdt -bcdt -s ../data/output/109-1.txt -conf ../conf/tools/showbcdt/atp-oc-bcst.txt -o ../data/output/atp-oc.txt


  备注：
  1）目的是截取一段区间。如果是endno大于实际的数据的最大数据号的，则最终截取实际数量的。
  例如oc只有[1, 100], 则如果-startno=1， -endno=1000,实际获取的数据范围是：[1, 100]

  2) 解析可视化数据是实际数据，不包含set,type，以及序号。 但是能够保证，数据是有序递增。具体数据列表是以上oc的数据范围。


  COPY UEXE:AM63.EXE AST591"NGTS_15 SHANGHAI"::TOFF$EXE: /FTP /L
  COPY UEXE:MAHBM001.EXE AST591"NGTS_15 SHANGHAI"::TOFF$EXE: /FTP /L

** 常用查询命令:
  订单簿: mcr tol$exe:showotw -ord -set 109 -time *,*
  rdrlog: mcr tol$exe:showwp -rdr -set 109 -time *,*
  广播内存: mcr tol$exe:showwp  -brc -set 109 -p EZEI0 -tp 19 -range *,*
  订阅内存: mcr tol$exe:showall -hhbm -subinfo
** OPENVMS下DEBUG程序:
  本地主机上: set display/create/trans=tcpip/node=本地主机ip
  开发主机上: 
  COPY U3$:[ATP04.DEV.SIR.33070]MSHDPT001.C   USRC /L 
  COPY U3$:[ATP04.DEV.SIR.33070]MSHDPT002.C   USRC /L
  COPY U3$:[ATP04.DEV.SIR.33070]SHOWOTW.C     USRC /L
  COPY U3$:[ATP04.DEV.SIR.33070]MSHCCR002.C   USRC /L

  perl utools:debug.pl
  设置debug窗口的IP地址:SET DISPLAY/CREATE/TRANS=TCPIP/NODE=196.131.3.78

** 修改系统文件后CONV：
  CONV /FDL=TOFF$FDL:FTBIZSTK USER_FTBIZSTK_FILE USER_FTBIZSTK_FILE /STAT

  @BACK01$:[AIR.SCRIPT]AUTO_RESTORE.COM BACK01$:[TOFF29.DATA.POST_BACKUP.POST_BACKUP_A040400_CUR_20070312] A

** Upgrade Back Env:
     @BACK01$:[AIR.SCRIPT]AUTO_RESTORE.COM BACK01$:[TOFF20.DATA.POST_BACKUP.POST_BACKUP_20070312] A
     @BACK01$:[AIR.SCRIPT]AUTO_RESTORE.COM BACK01$:[TOFF78.DATA.POST_BACKUP.POST_BACKUP_A040600_CUR_20070312] A

** dcl脚本调试
     set verify
     define toff$verify "ON"

** openvms delete file and directory:
      a. delete a file
      delete xxx.dat;1 /l

      b. delete all files in current dir:
      delete *.*.* /l

      c. delet a dir and all files in sub dir:
      set def xxxx
      dir
      delete [...]*.*.* /tree /l

** run a openvms file with process name:

      run /detatched/process=hibertrig hibertrig
      ana/sys
      show process hibertrig

      stop hibertrig

** OpenVms Copy a Locked file:
  conv /share file new_file /stat

** 查看或在所有的虚拟桌面切换: Win + Tab
      创建新的虚拟桌面: Win + Ctrl + D
      关闭当前虚拟桌面: Win + Ctrl + F4
      切换虚拟桌面: Win + Ctrl + L/F x
      虚拟桌面顺序:
      a. 编程环境
      b. 文档编辑
      c. 文档，书籍，资料查看

** Cmder 常用命令:
      Ctrl + Tab  : Swicth Between Tabs
      Ctrl + T    : Create a New Tab

** OpenVMS 管道
      pipe install list/global | sea sys$input 85_85

      the DCL pipe command under OpenVms:

      PIPE command-sequence [separator command-sequece]

      PIPE常用功能:
      a. 多命令同时执行
      PIPE command-sequence; command-sequence; [; command-sequence]

      b. 命令执行的条件化
      PIPE command-sequence1 && command-sequence2
      PIPE command-sequence1 || command-sequence2

      c. 命令执行的管道化
      PIPE pipeline-segment | pipeline-segment [|...]

      d. Subshell excution
      PIPE ( command-sequence [ separator command-sequence]...)

      e. Background excution
      PIPE command-sequence [ separator command-sequence]... &

** DWR脚本编译:

      BACK01$:[PATCH.DWRTOOL.DWR.DWR_JH]
      $ SET DEF BACK01$:[PATCH.DWRTOOL]
      @[.TOOLSET]DWR_SETENV JH
      DWR$LOAD
      perl dwrtool.pl -c DEBUG.CONF -l JH -n JH
      DWR$EXTRACT
      DWR$QUIT

      perl private_tools\ATP\AIR_FEEDER_BECMD.PL AST591 "perl TOL$DCL:BIZTOOL.PL -m TR0000400023590000" " : [TRYYYYYYYYYYYYYYYY0000400023590000]" search

** 常用主机IP地址:
      dev03 : 172.23.1.101

** 开发主机上代码作QA检查
      @dtools:check_qa xxxx.c SIR [ADD|REPLACE|...]

** 竟价模拟器:
      http://svn.tc.com/TOOLDoc/TestTools/MTPEMulator/MTPEmulator文档.docx
      U3$:[RXCHEN.DEV.SRC]TEST_SIM.C;59
** trunc
      set def data02$:[000000]
      set file /trunc [...]*.*
** Openvms条件编译:
      comp xxxx /define=TEST
      is same as:
      #define TEST 1

      /DEFINE="funct(a)=a+sin(a)"
      This definition produces the same results as the following definition:
      #define funct(a) a+sin(a)

      gcc条件编译:
      gcc xxxx.c -D TRUE
      is same as use this macro in xxxx.c

      #define TRUE 1

      mcr NGTS_SYS$:[TOFF55.TOOLS.EXE_I64]XDATA.EXE AGP101$:[TOFF55.DATA.FILES]FPSERI20106.RUJ  toff$fdl:RMSERI2T.FED toff$work_Dir:hjiang_ser2.csv
** 后台环境主机确认
   SEA USER_FTOP_MSG_FILE "MASTER HRRM"
   显示:
   [INFORMATION] HRRM on Host(XXXX) is the Master HRRM 
** OpenVms Command Reuslt to file:
   assign/user_mode test.txt sys$output
   your command
   deassign/user_mode sys$output
** OpenVms Create an empty file:
   copy nl: file.txt
** OpenVms Device Operation:...
   SHOW DEV DSA /UNIT=BYTE
   PURGE [...] /L
** Upgrade
   @BACK01$:[TOFF15.DATA.POST_BACKUP]POST_RESTORE_CNTRL.COM 
** ATP Commands...
   @BACK01$:[AIR.SCRIPT]QUICKKILLENV.COM
** OpenVMS Trace Net Packages...
   tcptrace 198.1.75.1 /PORT=LOCAL=11518 /PACKETS=1000 /out=toff$work_dir:hjiang_11518.txt
   tcptrace 198.1.186.1 /PORT=LOCAL=11518 /PACKETS=1000 /out=toff$work_dir:hjiang_11518.txt
* Atp Platform...
** AM67 Market Data
   应用进程 --> 写入 --> WP ---读取---> AM67 ---> 行情文件 ---> EI

   Arch Init:
   1. AppShl Init:
      异步进程
      无SET
      无WP
   
      AppShlRegTimer注册定时器

   2. 行情落地方式

* Atp Frame Test
** upgrade to latest atp version
   @BACK01$:[TOFF15.DATA.POST_BACKUP]POST_RESTORE_CNTRL.COM
   BACK01$:[TOFF27.DATA.POST_BACKUP.POST_BACKUP_A050000_AST_20070312]
** front end order sending (iterate)
   file:/d/Org/Atp/FrameTest/allatp.sql
** set 100 test
| set | order book size | order number(when switch) | pbu status (Normal/Abnormal) | order resp(Normal/Abnormal) | v_log  | front and back diff(Same/Diff) |
|-----+-----------------+---------------------------+------------------------------+-----------------------------+--------+--------------------------------|
| 100 |         1000000 |                    521534 | Normal                       | Normal                      | NO_ERR | Same                           |
| 101 |          400000 |                           |                              |                             |        |                                |
| 102 |                 |                           |                              |                             |        |                                |
| 104 |                 |                           |                              |                             |        |                                |
| 105 |                 |                           |                              |                             |        |                                |
| 106 |                 |                           |                              |                             |        |                                |
| 109 |                 |                           |                              |                             |        |                                |

* Core PlatFrom Auto Run:
** SVN
   http://svn.tc.com/MultiGroupTask///trunk/
** Upgrade
   cd /cygdrive/y/DevRelease/ATP_AUTO_INTEG/A050000  
   tel 198.1.153.1
   set def BACK01$:[PATCH.15.A050000_AC_PATCH]
   @BACK01$:[AIR.SCRIPT]AUTO_RESTORE.COM BACK01$:[TOFF55.DATA.POST_BACKUP.POST_BACKUP_A040700_CUR_20070312] "" temp01$:[testenv_Data.atp.dst]DST_ENV_CFG.BCK

   ./AtpCode/DDCL/POST_RESTORE_CNTRL.COM:1736:         " PLEASE ENTER THE USER FOR THE CS:[DEFAULT ''TCG_USR_CS_NET']"
   ./AtpCode/DDCL/POST_RESTORE_CNTRL.COM:1741:         " PLEASE ENTER THE PASSWORD FOR THE CS:[USER ''TCG_USR_CS_NET_TMP']"
   
   ./AtpCode/DDCL/TOFF_ONLINE_MANAGEMENT.COM:113:$ ASK_FOR_TC_PWD = """''SHIFT'PLEASE ENTER ''TCG_USR_HD_ADM' PASSWORD ON TC: """
   ./AtpCode/DDCL/TOFF_ONLINE_MANAGEMENT.COM:140:$ ASK_FOR_CS_PWD = """''SHIFT'PLEASE ENTER ''TCG_USR_CS_ADM' PASSWORD ON CS: """
   ./AtpCode/DDCL/TOFF_ONLINE_MANAGEMENT.COM:164:$ ASK_FOR_EI_PWD = """''SHIFT'PLEASE ENTER ''TCG_USR_EI_ADM' PASSWORD ON EI: """

   Q1: cscheck 若填201(不是0201), 结点范围检查错误

   bashftp ./PATCH_DATA.COM BACK01$:[PATCH.15.A050000_AC_PATCH] u
   bashftp ./GEN_PATCH_SCRIPT.PL BACK01$:[PATCH.15.A050000_AC_PATCH] u
   bashftp ./UPGRADE_VMS.COM BACK01$:[PATCH.15.A050000_AC_PATCH] u
  
   COPY [.GENERIC.15]FPENVCONF_AC.DAT 198.1.40.1"NOP_15 SHANGHAI"::TOFF$:[TOFF15.DATA.FILES]FPENVCONF.DAT /FTP /L
   COPY [.GENERIC.15]FPENVCONF_AC.DAT 198.1.46.1"NOP_15 SHANGHAI"::TOFF$:[TOFF15.DATA.FILES]FPENVCONF.DAT /FTP /L

   @BACK01$:[TOFF15.DATA.POST_BACKUP]POST_RESTORE_CNTRL.COM

   %PURGE-W-SEARCHFAIL, error searching for DSA0:[TOFF15.SYSTEM.EXE]*.EXE;*
   -RMS-E-FNF, file not found
   %PURGE-W-SEARCHFAIL, error searching for DSA0:[TOFF_NET15.DCL]*.COM;*
   -RMS-E-FNF, file not found
   
   CSGW1$:[MP130.HK001]REFF04020070613001.TXT
   
   CREATE/DIR AGP101$:[TOFF15.DATA.WORK.OAT]
   define toff$oat_status AGP101$:[TOFF15.DATA.WORK.OAT] /G
** CORE Plat MENU UPGRADE
** Batch File List:
*** 综业EI下线版本计划:

   | 批次 | 下线内容                                                        | 原则                                      | 预计开发时间             |
   |------+-----------------------------------------------------------------+-------------------------------------------+--------------------------|
   |    1 | 从EzPAR接收的文件(2个), 向EzPAR发送的文件(2个)                  | 选择所内系统[重要程度低]收发文件下线      | 2018/8/25 -- 2018/9/15   |
   |    2 | 所有所内系统收发文件下线[NGTS,信息公司,信息中心,业务管理系统等] | 所有所内系统收发文件下线,菜单收发文件下线 | 2018/9/15 -- 2018/10/15  |
   |    3 | 所外系统收发文件下线[中登,港交所等]                             | 所有收发文件下线,包括批处理和菜单         | 2018/10/15 -- 2018/11/15 |


   | 菜单项    | 源文件 | 目地地 | 脚本 | 改动 |
   |-----------+--------+--------+------+------|
   | M-8-1 and |        |        |      |      |

   | BATCH_NUM | BATCH_NAME        | FILENAME              | FROM                     | TO                | DEAD_LINE | IN/OUT |   |   |   |   |
   |-----------+-------------------+-----------------------+--------------------------+-------------------+-----------+--------+---+---+---+---|
   |     77500 | SEND_SSJG         | USER_FNSSJG_FILE      | TOFF$TO_SGE              | TOFF$MP128_SE030  |    153000 | O      |   |   |   |   |
   |     78200 | GEN_ZRTSB_FILES   | USER_FNZRTCJSB_FILE   | TOFF$TO_NGTS             | TOFF$MP001_SE030  |    153000 | O      |   |   |   |   |
   |     78400 | GEN_ZRT_FILES     | USER_FNZRTCJ_FILE     | TOFF$TO_IS               | TOFF$MP100_SE030  |    201500 | O      |   |   |   |   |
   |     81200 | GEN_VTE_FILES     | USER_FNVTOD_FILE      | TOFF$TO_IS               | TOFF$MP005_SE030  |    180000 | O      |   |   |   |   |
   |     77600 | WAIT_SSMX_FILE    | USER_FNSSMX_FILE      | TOFF$MP030_SG001         | TOFF$FROM_SGE     |    153000 | I      |   |   |   |   |
   |     76500 | GEN_BJCR          | USER_FNBJCR0_FILE     | TOFF$TO_SDC              | TOFF$MP110_SE001  |    153000 | O      |   |   |   |   |
   |           |                   | USER_FNTRDS01_FILE    | TOFF$TO_SDC              | TOFF$MP110_SE030  |    153000 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     76300 | GEN_BGH           | BGHZIP                | use: toff$exe:FCFCHG.EXE |                   |           | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     75300 | WAIT_AGKYYE_FILE  | USER_FNAGKYYE_FILE    | TOFF$MP030_SE001         | TOFF$FROM_NGTS    |    154000 | I      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     75200 | GEN_BT_FILES      | USER_FNDGHZIP_FILE    | TOFF$TO_NGTS             | TOFF$MP102_SE030  |    154500 | O      |   |   |   |   |
   |           |                   | USER_FNDZAG0_FILE     | TOFF$TO_SDC              | TOFF$MP109_SE004  |    160000 | O      |   |   |   |   |
   |           |                   | USER_FNDZBG0_FILE     | TOFF$TO_SDC              | TOFF$MP109_SE004  |    160000 | O      |   |   |   |   |
   |           |                   | USER_FNDZCJ_FILE      | TOFF$TO_IS               | TOFF$MP003_SE030  |    153300 | O      |   |   |   |   |
   |           |                   | USER_FNDZSB_FILE      | TOFF$TO_IS               | TOFF$MP003_SE030  |    153300 | O      |   |   |   |   |
   |           |                   | USER_FNDZYX_FILE      | TOFF$TO_IS               | TOFF$MP003_SE030  |    153300 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     75202 | PRCS_DZJCRD       | USER_FNJJKYED_FILE    | TOFF$TO_NGTS             | TOFF$MP001_SE030  |    160000 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     75204 | WAIT_JJRDSJ       | USER_FNAGXSYE_FILE    | TOFF$MP030_SE001         | TOFF$FROM_NGTS    |    154000 | I      |   |   |   |   |
   |           |                   | USER_FNJJRDJG_FILE    | TOFF$MP030_SE001         | TOFF$FROM_NGTS    |    160000 | I      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     75203 | SEND_BT_FILES     | USER_FNAGXSCJ_FILE    | TOFF$TO_SDC              | TOFF$MP109_SE001  |    163000 | O      |   |   |   |   |
   |           |                   | USER_FNDZJCBB_FILE    | TOFF$TO_NGTS             | TOFF$MP100_SE001  |    163000 | O      |   |   |   |   |
   |           |                   | USER_FNYYJCBB_FILE    | TOFF$TO_NGTS             | TOFF$MP049_SE030  |    160000 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     77300 | SEND_SPSJ         | USER_FNSPSJ_FILE      | TOFF$TO_NGTS             | TOFF$MP001_SE030  |    160000 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     76400 | GEN_AGCC          | USER_FNBGHZIP_FILE    | TOFF$TO_NGTS             | TOFF$MP001_SE030  |    153000 | O      |   |   |   |   |
   |           |                   | USER_FNAGCC_FILE      | TOFF$TO_NGTS             | TOFF$MP102_SE030  |    154500 | O      |   |   |   |   |
   |           |                   | USER_FNBGCC_FILE      | TOFF$TO_NGTS             | TOFF$MP102_SE030  |    154500 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     76800 | GEN_ZYYE          | SE030ZYYE             | use: toff$exe:FCFCHG.EXE |                   |           | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     77700 | GEN_DDRZ          | USER_FNDDRZ_FILE      | TOFF$TO_IS               | TOFF$MP003_SE030  |    200000 | O      |   |   |   |   |
   |     77010 | GEN_TRDS02        | USER_FNTRDS02_FILE    | TOFF$TO_SDC              | TOFF$MP110_SE030  |    160000 | O      |   |   |   |   |
   |     41280 | GEN_PBULOGIN_INFO | USER_FNPBULOG_FILE    | TOFF$TO_STC              | TOFF$MP027_SE030  |    190000 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     75600 | WAIT_EZPAR_FILE   | USER_FNBRKAUTEXP_FILE | TOFF$MP030_SE902         | TOFF$FROM_EZPAR   |    201500 | I      |   |   |   |   |
   |           |                   | USER_FNBIZSTKEXP_FILE | TOFF$MP030_SE902         | TOFF$FROM_EZPAR   |    201500 | I      |   |   |   |   |
   |           |                   | USER_FNHYXXEXP_FILE   | TOFF$MP030_SE902         | TOFF$FROM_EZPAR   |    201500 | I      |   |   |   |   |
   |           |                   | USER_FNPBUAUTEXP_FILE | TOFF$MP030_SE902         | TOFF$FROM_EZPAR   |    201500 | I      |   |   |   |   |
   |           |                   | USER_FNACCAUTEXP_FILE | TOFF$MP030_SE902         | TOFF$FROM_EZPAR   |    201500 | I      |   |   |   |   |
   |           |                   | USER_FNZLWJ_FILE      | TOFF$MP030_SE902         | TOFF$FROM_EZPAR   |    201500 | I      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     75700 | PRCS_EZPAR_FILE   | USER_FNBRKAUTOUT_FILE | TOFF$TO_EZPAR            | TOFF$MP126_SE030  |    201500 | O      |   |   |   |   |
   |           |                   | USER_FNDLZH_FILE      | TOFF$TO_EZPAR            | TOFF$MP902_SE030  |    201500 | O      |   |   |   |   |
   |           |                   | USER_FNHYXXOUT_FILE   | TOFF$TO_EZPAR            | TOFF$MP126_SE030  |    201500 | O      |   |   |   |   |
   |           |                   | USER_FNPBUAUTOUT_FILE | TOFF$TO_EZPAR            | TOFF$MP126_SE030  |    201500 | O      |   |   |   |   |
   |           |                   | USER_FNRQXX_FILE      | TOFF$TO_EZPAR            | TOFF$MP129_SE030  |    201500 | O      |   |   |   |   |
   |           |                   | USER_FNACCAUTOUT_FILE | TOFF$TO_EZPAR            | TOFF$MP126_SE030  |    201500 | O      |   |   |   |   |
   |           |                   | USER_FNZLJG_FILE      | TOFF$TO_EZPAR            | TOFF$MP902_SE030  |    201500 | O      |   |   |   |   |
   |           |                   | USER_FNBIZSTKOUT_FILE | TOFF$TO_EZPAR            | TOFF$MP126_SE030  |    201500 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     71100 | WAIT_NEW_CQCX     | USER_FNCQBD_FILE      | TOFF$MP030_SE038         | TOFF$FROM_NGTS    |    200000 | I      |   |   |   |   |
   |           |                   | USER_FNCQCX_FILE      | TOFF$MP030_SE038         | TOFF$FROM_NGTS    |    200000 | I      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     81600 | WAIT_VTE_FILE     | USER_FNVTIN_FILE      | TOFF$MP030_SE038         | TOFF$FROM_NGTS    |    164500 | I      |   |   |   |   |
   |           |                   | USER_FNVTLS_FILE      | TOFF$MP133_SE038         | TOFF$FROM_NGTS    |    164500 | I      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     81700 | CHECK_VTE_FILE    | USER_FNVTLSGG_FILE    | TOFF$TO_IS               | TOFF$MP100_SE030  |    180000 | O      |   |   |   |   |
   |           |                   | USER_FNVTLSGG_FILE    | TOFF$TO_IS               | TOFF$HK001_SE030  |    180000 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     77400 | SEND_NGTS_FILE    | USER_FNCPSJ_FILE      | TOFF$TO_NGTS             | TOFF$MP001_SE030  |    180000 | O      |   |   |   |   |
   |           |                   | USER_FNINSJ_FILE      | TOFF$TO_NGTS             | TOFF$MP001_SE030  |    180000 | O      |   |   |   |   |
   |           |                   | USER_FNCKSJ_FILE      | TOFF$TO_NGTS             | TOFF$MP001_SE030  |    200000 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     14500 | WAIT_NGTS_FILE    | USER_FNATPZIP_FILE    | TOFF$MP030_SE001         | TOFF$FROM_NGTS    |    213000 | I      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     76600 | WAIT_SDC_FILES    | USER_FNAGXSJG_FILE    | TOFF$MP106_SC001         | TOFF$FROM_SDC     |    190000 | I      |   |   |   |   |
   |           |                   | USER_FNAZDJ_FILE      | TOFF$MP109_SE001         | TOFF$FROM_SDC     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNBGJZ_FILE      | TOFF$MP105_SC001         | TOFF$FROM_SDC     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNBJDJ1_FILE     | TOFF$MP105_SC001         | TOFF$FROM_SDC     |    220000 | I      |   |   |   |   |
   |           |                   | USER_FNBXWJ1_FILE     | TOFF$MP105_SC001         | TOFF$FROM_SDC     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNBZSL_FILE      | TOFF$MP102_CI001         | TOFF$FROM_SDC     |    160000 | I      |   |   |   |   |
   |           |                   | USER_FNFHQX_FILE      | TOFF$MP001_SE012         | TOFF$FROM_MIG     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNFLRELEASE_FILE | TOFF$MP142_SE012         | TOFF$FROM_MIG     |    220000 | I      |   |   |   |   |
   |           |                   | USER_FNJYQX_FILE      | TOFF$MP105_SC001         | TOFF$FROM_SDC     |    210000 | I      |   |   |   |   |
   |           |                   | SER_FNCPXX_FILE       | TOFF$MP100_SE001         | TOFF$FROM_NGTS    |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNPBUA_FILE      | TOFF$MP004_SE001         | TOFF$FROM_NGTS    |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNPBUB_FILE      | TOFF$MP004_SE001         | TOFF$FROM_NGTS    |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNZYDJ_FILE      | TOFF$MP030_SE001         | TOFF$FROM_NGTS    |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNZYYE_FILE      | TOFF$MP030_SE001         | TOFF$FROM_NGTS    |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNZHQX_FILE      | TOFF$MP030_SE001         | TOFF$FROM_MS      |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNHYPB_FILE      | TOFF$MP030_SE012         | TOFF$FROM_MIG     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNQISJ_FILE      | TOFF$MP030_SE012         | TOFF$FROM_MIG     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNQXKZ_FILE      | TOFF$MP001_SE012         | TOFF$FROM_MIG     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNZPBQ_FILE      | TOFF$MP030_SE012         | TOFF$FROM_MIG     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNBDZQ_FILE      | TOFF$MP125_SE001         | TOFF$FROM_EZTRANS |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNWDQY1_FILE     | TOFF$MP105_SC001         | TOFF$FROM_SDC     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNYWXZ_FILE      | TOFF$MP106_SC001         | TOFF$FROM_SDC     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNZQDJ1_FILE     | TOFF$MP105_SC001         | TOFF$FROM_SDC     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNZQMX1_FILE     | TOFF$MP105_SC001         | TOFF$FROM_SDC     |    210000 | I      |   |   |   |   |
   |           |                   | USER_FNZXCC_FILE      | TOFF$MP030_SE001         | TOFF$FROM_NGTS    |    210000 | I      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     76700 | CHK_SDC_FILES     | USER_FNBZSLGG_FILE    | TOFF$TO_NGTS             | TOFF$MP100_SE030  |    201500 | O      |   |   |   |   |
   |           |                   | USER_FNPAUTOUT_FILE   | TOFF$TO_NGTS             | TOFF$MP001_SE030  |    201500 | O      |   |   |   |   |
   |           |                   | USER_FNZRTBD_FILE     | TOFF$TO_NGTS             | TOFF$MP100_SE030  |    235900 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     76704 | WAIT_ZYLT_FILE    | USER_FNJJZYLT_FILE    | TOFF$MP030_SE001         | TOFF$FROM_NGTS    |    160000 | I      |   |   |   |   |
   |     76701 | WAIT_SFPM_FILE    | USER_FNSFPM_FILE      | TOFF$MPSHARE_SE023       | TOFF$FROM_FM      |    200000 | I      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     76702 | UPD_BRK_INFO      | HYXX                  | use: toff$exe:FCFCHG.EXE |                   |           | O      |   |   |   |   |
   |           |                   | BRQX                  | use: toff$exe:FCFCHG.EXE |                   |           | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     76710 | CHK_LOF_SFPM      | USER_FNSFPMDF_FILE    | TOFF$TO_FM               | TOFF$MP023_SE030  |    201500 | O      |   |   |   |   |
   |           |                   | USER_FNSFPMGG_FILE    | TOFF$TO_IS               | TOFF$MP100_SE030  |    203000 | O      |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
   |     77800 | GEN_RCDATA        | USER_FNINSTBIZ_FILE   | TOFF$TO_NGTS             | TOFF$MP036_SE030  |    220000 | O      |   |   |   |   |
   |           |                   | USER_FNSE030CPXX_FILE | TOFF$TO_NGTS             | TOFF$MP036_SE030  |    203000 | O      |   |   |   |   |
   |           |                   | USER_FNBRCREF_FILE    | TOFF$TO_NGTS             | TOFF$MP036_SE030  |    203000 | O      |   |   |   |   |
   |           |                   | USER_FNSE030LJXX_FILE |                          |                   |           |        |   |   |   |   |
   |           |                   |                       |                          |                   |           |        |   |   |   |   |
* EI Down
  ** DTP plat patches
  url:
  mcr toff$exe:ftdmon 

  create /dir AGP102$:[TOFF15.DATA.DISTRIBUTE.FROM_BPC] /L
  define toff$from_bpc AGP102$:[TOFF15.DATA.DISTRIBUTE.FROM_BPC] /G
* ToDoList
** <2018-07-17 ÖÜ¶þ>                                               :20180717:
*** DONE [#B] learn emacs org and make a todo list                      :org:
*** DONE [#A] get the feeling of the offle of EI                 :ei:offline:
*** TODO [#C] programming pearl, ch2 algorithm                    :algorithm:
*** code submit:
    [[file:code_submit.org][code_submit]]

** <2018-07-18 ÖÜÈý>
** <2018-07-20 ÖÜÎå>
** <2018-07-23 ÖÜÒ»>
* Working Notes
** <2018-08-27 周一>
   - [ ] 核心平台操作简化方案和计划展示
   - [ ] 综合业务平台EI下线计划和方案展示
** <2018-08-29 周三>
   - [ ] 操作简化单元测试用例完善
   - [ ] 操作简化问题单完善
   - [ ] EI下线一阶段开发计划和测试计划
* PatchMending
  ** 52265
  conv/fdl=toff$fdl:FTBIZSTK.FDL USER_FTBIZSTK_FILE USER_FNBIZSTK_FILE /STAT
  
  设置751800产品生效日为20070313
  conv/fdl=toff$fdl:FTBIZSTK.FDL USER_FTBIZSTK_FILE USER_FTBIZSTK_FILE /STAT
  conv/fdl=toff$fdl:FTBIZSTK.FDL USER_FNBIZSTK_FILE USER_FNBIZSTK_FILE /STAT

  @BACK01$:[AIR.SCRIPT]AUTO_RESTORE.COM BACK01$:[TOFF75.DATA.POST_BACKUP.POST_BACKUP_A040703_AST_20070312]

  ed /read USER_FPENVCONF_FILE
  
  assign/user_mode toff$work_dir:test.txt sys$output

  //恢复中断,导致系统logname lost
  set proc /priv=all
  @SYS$COMMON:[SYSMGR.SSE]TOFF$NGTS_STARTUP.COM @@ AC

  copy uexe:testseri2.exe ast591"ngts_75 shanghai"::toff$work_dir: /ftp /l
  
  error opening AGP202$:[TOFF75.DATA.FILES]FTQUOOTB.DAT;* as input

  @SYS$COMMON:[SYSMGR.SSE]TOFF$NGTS_STARTUP.COM 75 AC

  SET VERIFY
  SET PREFIX "(!12%T) "

  DEASSIGN SYS$OUTPUT
  DEASSIGN SYS$INPUT
  
  mcr tol$exe:XDATA.EXE USER_FNSERI20106_FILE  toff$fdl:RMSERI2T.FED toff$work_Dir:fnseri2.csv

  conv /fdl=FTBIZSTK.FDL USER_FNBIZSTK_FILE USER_FNBIZSTK_FILE /STAT

  copy toff$work_dir:MBH_UPD_INSTAT.EXE toff$exe: /l
  copy toff$work_dir:MBH_UPD_INSTAT.C toff$exe: /l
  copy toff$work_dir:BATAPPLSHL.C toff$exe: /l

  mcr toff$exe:ftdmon -d

  perl toff$work_dir:GETFILECSV.PL -b 76400 -o 76400.csv -l AST01 -r CSGWA
  perl toff$work_dir:GETFILECSV.PL -b 75300 -o 75300.csv -l AST01 -r CSGWA
  perl toff$work_dir:GETFILECSV.PL -b 75202 -o 75202.csv -l AST01 -r CSGWA
  perl toff$work_dir:GETFILECSV.PL -b 75204 -o 75204.csv -l AST01 -r CSGWA
  perl toff$work_dir:GETFILECSV.PL -b 75203 -o 75203.csv -l AST01 -r CSGWA
  perl toff$work_dir:GETFILECSV.PL -b 75200 -o 75200.csv -l AST01 -r CSGWA
  perl toff$work_dir:GETFILECSV.PL -b 77300 -o 77300.csv -l AST01 -r CSGWA
  perl toff$work_dir:GETFILECSV.PL -b 76400 -o 76400.csv -l AST01 -r CSGWA
  perl toff$work_dir:GETFILECSV.PL -b 77000 -o 77000.csv -l AST01 -r CSGWA  

  perl toff$work_dir:GETFILECSV.PL -b 41280 -o 41280.csv -l AST01 -r CSGWA  

  perl toff$work_dir:GETFILECSV.PL -b 75600 -o 75600.csv -l AST01 -r CSGWA  

  perl toff$work_dir:GETFILECSV.PL -b 76600 -o toff$work_dir:76600.csv -l AST01 -r CSGWA  
  perl toff$work_dir:GETFILECSV.PL -b 76700 -o toff$work_dir:76700.csv -l AST01 -r CSGWA  
  perl toff$work_dir:GETFILECSV.PL -b 76704 -o toff$work_dir:76704.csv -l AST01 -r CSGWA  


  create USER_FNDZJCBB_FILE /L
  create USER_FNYYJCBB_FILE /L
  create USER_FNDGHZIP_FILE /L
  create USER_FNDZCJ_FILE /L
  create USER_FNDZSB_FILE /L
  create USER_FNDZYX_FILE /L

  create USER_FNSPSJ_FILE /L

  create USER_FNAGCC_FILE /L
  create USER_FNBGCC_FILE /L

  create USER_FNBRKAUTOUT_FILE /L
  create USER_FNDLZH_FILE /L
  create USER_FNHYXXOUT_FILE /L
  create USER_FNPBUAUTOUT_FILE /L
  create USER_FNRQXX_FILE /L
  create USER_FNACCAUTOUT_FILE /L
  create USER_FNZLJG_FILE /L
  create USER_FNBIZSTKOUT_FILE /L

  @TOFF$DCL:FLAGGEN USER_FNDZJCBB_FILE TOFF$TO_NGTS:
  @TOFF$DCL:FLAGGEN USER_FNYYJCBB_FILE TOFF$TO_NGTS:
  @TOFF$DCL:FLAGGEN USER_FNDGHZIP_FILE TOFF$TO_NGTS:
  @TOFF$DCL:FLAGGEN USER_FNDZCJ_FILE   TOFF$TO_IS:
  @TOFF$DCL:FLAGGEN USER_FNDZSB_FILE   TOFF$TO_IS:
  @TOFF$DCL:FLAGGEN USER_FNDZYX_FILE   TOFF$TO_IS:
  @TOFF$DCL:FLAGGEN USER_FNSPSJ_FILE   TOFF$TO_NGTS:

  @TOFF$DCL:FLAGGEN USER_FNZRTCJ_FILE TOFF$TO_IS:
  @TOFF$DCL:FLAGGEN USER_FNVTOD_FILE TOFF$TO_IS:

  @TOFF$DCL:FLAGGEN USER_FNBGHZIP_FILE TOFF$TO_NGTS:
  @TOFF$DCL:FLAGGEN USER_FNJJKYED_FILE TOFF$TO_NGTS:

  @TOFF$DCL:FLAGGEN USER_FNAGCC_FILE TOFF$TO_NGTS:
  @TOFF$DCL:FLAGGEN USER_FNBGCC_FILE TOFF$TO_NGTS:

  BZSL

  bzsl01120070313001.txt                                      |276             |20181016|084124|12          |587E497F3A0564082A305C91566404DA |
  BZSL01120070313001.TXT                                      |276             |20181016|084057|12          |587E497F3A0564082A305C91566404DA |
                                                                                                             DD191C5A1E608DC200448FB119AC15F4

  openvms: F5096D43644462437C57059DAA79A2C8

  linux:   587e497f3a0564082a305c91566404da

  origi:   587E497F3A0564082A305C91566404DA

  sed '/\$! MCR TOFF$EXE:FCFCHG.EXE -f/d' *
* Latex...
** LaTeX Special Character
   [character]		[Purpose]
   #
   $
   %			LaTeX comments
   			Can also be used to split long input lines where no
			whitespace or line breaks are allowed
   ^
   &
   _
   {			LaTeX parameters begin
   }			LaTeX parameters end	\command[optional parameters]{parameters}
   ~
   \			LaTeX command

** LaTeX Input File Structure
   \documentclass{...}
   \usepackage{...}
   \begin{document}
   \end{document}

   tipical LaTeX command line session
   1. use Emacs(or other editor) edit source file
   2. shell or cmd.exe
      latex test.tex
   3. look at the file on screen
      linux/unix: xdvi test.dvi &
      windows: yap test.dvi

      convert the dvi file to PostScript
      dvips -Pcmz test.dvi -o test.ps

      convert the dvi file to pdf
      dvipdf test.dvi

** The Layout Of A Doucument
   3.1 documentclass
   [type]			[usage]
   article			scientific journals, presentations, short reports,
                    program docmentation, invitations, ...
   proc				a class for proceedings based on the article class
   minimal			as small as possible
   report			longer reports containing several chapters,
   				    small books, PhD theses, ...
   book 			for real book
   slides
   3.2 packages
   3.3 pagestyle
      
* Useful links...
** 用perl产生OPENVMS DCL脚本，并在后台执行这个脚本，
   将这个脚本的执行结果收集文件中
   [[file:d:/Org/TaskDir/EIDown2/TaskTest/GetAllBatchFileName/GetFileName.pl][GetFileName.pl]]
** 获取后台代码的PERL脚本和包装在其上的SHELL脚本
   [[file:~/MyBin/get_source.pl][get source]]
   [[file:~/MyBin/GetSource][GetSource, bash script]]

** EI下线任务相邻两期配置文件比对，并产生增量升级配置文件...
   [[file:d:/Org/TaskDir/EIDown2/TaskTest/IncreGen.pl][IncreGen.pl]]
   [[file:~/MyBin/IncreGen][IncreGen(Bash Wrapper file)]]
* Hacking(Good and Bad taste)...
** emacs and emacs lisp
*** Give a man a new Emacs command and he can hack for a night;
    Teach a man to make new Emacs commands and he can hack for a lifetime.
*** Common Lisp: A gentle introduction to Symbolic Computation
*** Writing gnu emacs extensions...
    - [] ch1, Customizing Emacs
         A. Binding Keystrokes to Commands
            (global-set-key keysequence command)
         example:
            (global-set-key "\M-?" 'help-command)

         B. Emacs most important online help : apropos
         function : allows you to search all known variables and functions
                    for a pattern you specify.
         
         hsha ash
    - [] ch2, Simple New Commands
    - [] ch3, Cooperating Commands
    - [] ch4, Searching and Modifying Buffers
    - [] ch5, Lisp Files
    - [] ch6, Lists
    - [] ch7, Minor Mode
    - [] ch8, Evauation and Error Recovery
    - [] ch9, A Major Mode
    - [] ch10, A Comprehensive Example
    - [] Appendix xxx
* Golang...
** Install go packages online or offline
*** online: 
    以go-sbvector包为例, 
    go get github.com/hideo55/go-sbvector
    上指令执行成功后程序调用
    import (
        "github.com/hideo55/go-sbvector"
    )

    offline:
    在能连网的主机上执行online安装好package
    查看这台连网主机的GOPATH,
    go env
    将GOPATH中新安装的package拷备到目标主机的GOPATH中
** composite type
*** slice
    slices can't be compared
* Task...
  pipe show system | sea sys$input MAHBM001
  stop/id=2023F14B
  SET DISPLAY/CREATE/TRANS=TCPIP/NODE=196.131.8.129
  mcr toff$work_dir:MAHBM001.EXE
  MAHBM001,IPCS_SOCKET,IPCS_UCX_PLUG,STREAMIO
  gcc -o Client CClient.c netmsg.c -lpthread
  mcr tol$exe:showwp  -brc -set 106 -p ezei0 -tp 37 -range *,*

  1. 根据测试组架构测试报告, 综业定单成交簿打满之后, 批处理可以正常进行;
  2. 综业出现每秒上千笔定单的情形,跨平台消息管理器(CPCM)主处理会被跨平台请求处理占用,会导致跨平台响应处理的延迟;
  3. 如果综业瞬时定单量继续升高, 跨平台消息管理器(CPCM)队列会被打满, 导致跨平台请求丢失, 出现丢单情况;
     目前综业平台存在跨平台的业务:
     a) 分级基金母基金和子基金的拆分合并;
     b) ETF业务
     c) 大宗交易成交买卖, 大宗资产证券化成交买卖,集合资产管理计划成交买卖
     d) 非公开发行优先股成交卖单和撤单
     e) 大宗盘后固定价格
     f) 转融通
     g) 国债预发行
     h) 投票业务
  4. 港股通平台定单簿和成交簿大小配置为2kw, 但由于发往EzEI定单会占用广播消息表(表大小为2kw), 广播消息表无法支持2kw的成交. 所以目前港股通支持的最大定单量无法达到1kw, 但目前港股通每日定单
     量只有11w左右;
  5. 港股通定单和成交数量超过45w时, 闭市时落OTB的时间超过30s,导至EzEI在这段时间收不到港股通后台心跳,EzEI发生切换,但不会对业务处理造成影响;
  6. 观察最近多日综业和港股通定单簿和成交簿的占用比:
     1) 回购类业务定单簿使用比例最高, 每天维持在10%左右;
     2) 大宗交易业务定单簿使用比例约为0.01%, 成交数量维持在每天20笔左右,成交簿使用可以忽略不计;
     3) 跨境ETF业务定单簿使用比例不超过2%;
     4) 转融通业务定单簿使用比例不超过1%, 成交簿使用可以忽略不计;
     5) 货币基金及LOF业务定单簿使用比例不超过5%;
     6) 国债预发行业务定单簿一直为空;
     7) 投票类业务定单簿使用比例不超过0.2%;
     判断综业和港股通平台可以承受目前的市场定单活跃的情况.

  7. 综业和港股通平台运营监测点:
     a) 每台主机工作页面配置和当日使用比例;
     b) 每台主机消息缓存配置和当日使用比例;
     c) 每个产品集定单簿和成交簿配置和当日使用比例;

* GoLang...
** Go at Google: Language Design in the Service of Software Engineering
   [[https://talks.golang.org/2012/splash.article][Go at Google]]
