* Org Mode
** Outline and Writing                                               :hjiang:
*** insert heading
 M-Enter will insert a heading in current position
         and the newly heading is same with privious heading
*** promote heading
 M-Left  will promote the heading by one level
*** demote heading 
 M-Right will demote the heading by one level
*** promote entire subtree
 M-Shift-Left will promote an entire subtree
*** demote entire subtree
 M-Shift-Right will demote an entire subtree
** Plain List
** unordered plain list
   - first subitem
   - second subiten
     + another item
     + some thing else

(- or +) then press M-Enter, org mode will add a (- or +) automatically
** ordered plain list
   1. this is the first item
   2. this is the second item
   3. hsh
   4. this is the trird item
(1.) then press M-Enter, org mode will add a (2.) automatically
** add a checkbox
   - [ ] this is fiest checkbox
   - [ ] this is second checkbox
   - [ ] this is third checkbox
start the line with - [ ], toggle the check box using C-c C-c
** hyper links                                           :hyper_links_in_org:
** simple urls
http://www.baidu.com
** simple file path
file:/etc/file.pdf
** plain-text tables
 | name   | sex | age | number |
 |--------+-----+-----+--------|
 | hjiang | man | 23  | 234    |
 |        |     |     |        |
 |        |     |     |        |
 |        |     |     |        |
** tags                                                        :org_set_
* Emacs+Git => Magit
** magit-status : to display information about the current Git repository 
** p,n : Move between sections using ~p~ and ~n~.
   [tab]: expand or collapse the section at point.
   staging:         ~s~ to stage the changes you have made to specific file.
   unstaging:       (~u~) commands operate on the change at point
   commit:          And then of course you want to commit your changes.  Type ~c~.
   common commit:   We want to create a "normal" commit, which is done by typing ~c~ again
   real commit:     Write a message and then type ~C-c C-c~ to actually create the commit.
   push:            ~P~ to bring up the push popup
                    ~p~ to push to a branch with the same name as the local branch onto the
                    remote configured as the push-remote
