* Org Mode
** Outline and Writing
*** insert heading
    M-Enter will insert a heading in current position
        and the newly heading is same with privious heading
*** promote heading
    M-Left  will promote the heading by one level
*** demote heading 
    M-Right will demote the heading by one level
*** promote entire subtree
    M-Shift-Left will promote an entire subtree
*** demote entire subtree
    M-Shift-Right will demote an entire subtree
** Plain List
*** unordered plain list
   - first subitem
   - second subiten
     + another item
     + some thing else

(- or +) then press M-Enter, org mode will add a (- or +) automatically
*** ordered plain list
   1. this is the first item
   2. this is the second item
   3. hsh
   4. this is the trird item
(1.) then press M-Enter, org mode will add a (2.) automatically
*** add a checkbox
   - [ ] this is fiest checkbox
   - [ ] this is second checkbox
   - [ ] this is third checkbox
start the line with - [ ], toggle the check box using C-c C-c
** hyper links
*** simple urls
    http://www.baidu.com
*** link to file
    file:/files.txt
** tables
* Gdb usage
** compiling source file to debug            :symbolic:dubugging:information:
   gcc -g test.c -o test
   g++ -g test.cpp -o test

** debug in a gui mode
   gdb -tui
   arrow and page(down/up) key will srcoll the source window
   
   >list test.c:4 will bring up the file test.c on line 4

   >r or >run will run the program
   >r arg1 arg2 will run the program with the arguments

** break point
   >b main        :break at the main function
   >b 5           :break at the 5th line
   >b test.c:5    :break at line 5 of test.c

   >i b           :(info b) get the infomation of the break point

*** disable a break
   >disable 1     :disable the first break
   >clear main    :clear the break "main"


*** stepping
    >n             :move you to the next statement
    >s             :step into a function
    >c             :continue excution
    >[Enter]       :repeat last command you input

*** examing varible
   >disp i               :display the variable i, and display it every time you stop code
   >undisp i             :undisplay
   >info display
   >print i              :one-off display
   >printf "format" i    :format display

** misc stuff

*** backtrace
    >backtrace            :(bt) show current function call stack

*** addtional stepping
    >finish               :exit current excution function and return to the calling function
    >stepi                :step a single assembly instuction
    >advance loc          :coutinue to this temp loc

*** jump to arbitrary section
    >jump 3               :jump to line 3

*** set variables and values
    >set (i=20)
    >set variable i = 40

*** hardware watch point
    >watch var
     
* Emacs+Git => Magit
** magit-status : to display information about the current Git repository 
** p,n : Move between sections using ~p~ and ~n~.
   [tab]: expand or collapse the section at point.
   staging:         ~s~ to stage the changes you have made to specific file.
   unstaging:       (~u~) commands operate on the change at point
   commit:          And then of course you want to commit your changes.  Type ~c~.
   common commit:   We want to create a "normal" commit, which is done by typing ~c~ again
   real commit:     Write a message and then type ~C-c C-c~ to actually create the commit.
   push:            ~P~ to bring up the push popup
                    ~p~ to push to a branch with the same name as the local branch onto the
                    remote configured as the push-remote

* unix/linux
** append one file to another file's tail
   cat file1.txt >> file2.txt
** something about using git
*** initialize a empty Git repository :
   git init

   The previous command will init a '.Git' directory in
   current directory. the structure of this directory is
   like:
   -----------------------------------------------------
   HEAD
   config
   description
   hooks/
   info/
   objects/
   refs/
   -----------------------------------------------------
   Tips: config is the only file that we can change

*** git config
   config is done at 3 stages:
   1. system(--system)
   2. user(--global)
   3. project

   Example1:
   git config user.email hjiang@sse.com.cn

   The previous command will append two lines to "config" file:
   [user]
	email = hjiang@sse.com.cn


   Example2:
   git config --global user.name "hjiang"
   git config --global user.ID "0715039"

   the previous commands will add three lines to .gitconfig in $HOME
   [user]
       name = hjiang
       ID = 0715039

*** git arch
   view git in three level
   [level-1] User Working Dir
   [level-2] Stage(index)
   [level-3] Repository

   2-step process:
   lev-1 ---> lev-2 : git add
   lev-2 ---> lev-3 : git commit

   lev-3 ---> lev-2 : git reset --
   lev-2 ---> lev-1 : git checkout --

   1-step process:
   lev1-->lev2-->lev3 : git commit -a
   lev3-->lev2-->lev1 : git checkout HEAD --

   2.4 git updating repository
   git add filename
   git commit -m "some kind of message"

   2.5 git checkout

   a. to the latest version:
      git checkout -- filename

   b. to any previous version:
      git log
      the previous command will get commit infomation:

   commit 34ccee5100c00b2668f9f785c000e8ae75c9d73a
   Author: hjiang <hjiang@sse.com.cn>
   Date:   Mon Nov 6 11:10:53 2017 +0800

       add a line in File1.txt

   commit 25f65bf8abd9190509dbdd19ee97593318fe1c43
   Author: hjiang <hjiang@sse.com.cn>
   Date:   Mon Nov 6 11:02:28 2017 +0800

       First line was written at file1.txt

   commit a11b757a56870313c98e86d476416158f0cd2925
   Author: hjiang <hjiang@sse.com.cn>
   Date:   Mon Nov 6 10:59:00 2017 +0800

       This is a test of git commit
   
** introduce to make file:
   /src : contain source file
          main.cpp, extra.cpp, other.cpp
   /bin : contain dest binary file

   makefile:
   bin/myprogm: src/extra.cpp src/main.cpp src/other.cpp
       g++ $^ -o $@

   then in command line:
   make
   or make -B

** split a text file in to a word list
   tr -s '[[:punct:][:space:]]' '\n' < testfile.txt
** find command
*** find a string in a directory[the directory have multi files]
    grep -rnw '/path/to/somewhere/' -e 'pattern'
*** find a file bigger or smaller than a given size 
    find . -type f -size +6096c [find files bigger than 6096bytes]
   find . -type f -size -6096c [find files smaller than 6096bytes]


          -size n[cwbkMG]
              File uses n units of space, rounding up.  The following suffixes
              can be used:

              `b'    for  512-byte blocks (this is the default if no suffix is
                     used)

              `c'    for bytes

              `w'    for two-byte words

              `k'    for Kilobytes (units of 1024 bytes)

              `M'    for Megabytes (units of 1048576 bytes)

              `G'    for Gigabytes (units of 1073741824 bytes)

              The size does not count  indirect  blocks,  but  it  does  count
              blocks in sparse files that are not actually allocated.  Bear in
              mind that the `%k' and `%b' format specifiers of -printf  handle
              sparse   files  differently.   The  `b'  suffix  always  denotes
              512-byte blocks and never 1 Kilobyte blocks, which is  different
              to  the  behaviour of -ls.  The + and - prefixes signify greater
              than and less than, as usual, but bear in mind that the size  is
              rounded  up to the next unit (so a 1-byte file is not matched by
*** linux 在一个文件夹中的所有文件中查找一个字符串:
  grep -rnw '/path/to/somewhere/' -e 'pattern'
  r: recursive
  n: number of the line
  w: match the whole word

  search the files which have .c or .h extensions:
  grep --include=\*.{c,h} -rnw 'path/to/somewhere' -e 'pattern' 

  exclude searching all the files ending with .o extension:
  grep --exclude=\*.o -rnw 'path/to/somewhere' -e 'pattern' 

  --exclude-dir, --include-dir

*** Search a file with a specific name:
    hjiang@hjiang:~/Gitspace/TestSpace/ROOT$ tree                                                                                                                          
.                                                                                                                                                                      
├── DIR1                                                                                                                                                               
│   ├── fileA.c                                                                                                                                                        
│   └── fileB.c                                                                                                                                                        
├── DIR2                                                                                                                                                               
│   ├── #fileC.c#                                                                                                                                                      
│   └── fileC.c                                                                                                                                                        
├── GPATH                                                                                                                                                              
├── GRTAGS                                                                                                                                                             
├── GTAGS                                                                                                                                                              
└── README   
    
    This is the tree structure of /ROOT directory.
    
    hjiang@hjiang:~/Gitspace/TestSpace/ROOT$ find . -name fileC.c                      |├── GRTAGS                                                                        $
    ./DIR2/fileC.c

*** Search files with a pattern:
    hjiang@hjiang:~/Gitspace/TestSpace/ROOT$ find . -name *.c                                                                                                              
    ./DIR2/.#fileC.c                                                                                                                                                       
    ./DIR2/fileC.c                                                                                                                                                         
    ./DIR1/fileA.c                                                                                                                                                         
    ./DIR1/fileB.c   
*** Find and delete a file with confirmation
    hjiang@hjiang:~/Gitspace/TestSpace/ROOT$ find . -name fileC.c -exec rm -i {} \;                                                                                        
    rm: remove regular file './DIR2/fileC.c'? n 
*** Search for empty file and directory
    find . -empty
*** Search for file with entered permission
    find . -perm 664
*** Search text within multiply files
    hjiang@hjiang:~/Gitspace/TestSpace/ROOT$ find . -type f -name "*.c" -exec grep 'func' {} \;                                                                            
    func2() { i++; }                                                                                                                                                       
    func2() { i--; }                                                                                                                                                       
    func3(){                                                                                                                                                               
            func1();                                                                                                                                                       
            func1();                                                                                                                                                       
            func2();                                                                                                                                                       
    func1() {...} 
** sed command
   essential command: s for substitution
   sed 's/one/ONE' file.txt
   s: substitution command
   /../../ : delemeter
   one : Regular expression Pattern Search Pattern
   ONE : Replacement string

   using & as the matched string:

   extened regular expression:
   echo "123 abc" | sed -r 's/[0-9]+/& &/'
   -r: stand for extented regular expression

   using \1 to keep part of the pattern:
   sed 's/\([a-z]*\).*/\1/' Basic.sh , will keep the first word of this line
   sed 's/\([a-z]*\) \([a-z]*\)/\2 \1/' Basic.sh , will switch two word
   sed 's/\([a-z][a-z]*\) \([a-z][a-z]*\)/\2 \1/' file.txt , ensure a word has least one letter

   sed -r 's/([a-z]+) ([a-z]+)/\2 \1/' file.txt , using extended regular expression
   sed -r 's/([a-z]+) \1/\1/' file.txt , \1 can occur in the pattern regular expression
   sed -nr '/([a-z]+) \1/p' file.txt , will detect duplicated words
   sed -r 's/(.)(.)(.)/\3\2\1/' file.txt, reverse first three cha on a line

   Sed Pattern Flag, specify what happens when a match is found
   sed 's/[^ ]*/(&)/' test.txt, this parenthesis around the first word
   sed 's/[^ ][^ ]*/(&)/g' test.txt, this parenthesis around all the word

   /1, /2 etc. Specifying witch occurrence
   sed -r 's/([a-zA-Z]*) ([a-zA-Z]*)/\1 /' test.txt, keep the first word on line and leave the next
   sed -r 's/([a-zA-Z]*) //1' test.txt, same as privious line
   sed -r 's/[a-zA-Z]* /DELETED /1g' test.txt
   sed 's/[a-zA-Z]* /DELETED /2g' test.txt

   sed -e 's/a/A/' -e 's/b/B' test.txt , multiple command with -e

** history command
     !! : repeat last command
     !ssh : recall last command start with ssh
     history : see the list of excuted command
     !13 : recall command with index is 13

** GNU global
   Move to a directory, then run "gtags" command.
   Then gtags will traverses sub-directories, pick up symbols from the source files
   and makes 3 tag files under current directory.
   
   GTAGS    definition database
   GRTAGS   reference database
   GPATH    path name database 
*** basic usage
   When we get the previous files, we can use them to:
   1. find the relative path of a symbol:
      global symbol-mame
   
   2. locate the refrence of a symbol:
      global -r symbol-name

   3. use posix regex find path of a symbol:
      global 'func[1-3]'

   4. show detail info of a symbol:
      gloabl -x func1
      
      hjiang@hjiang:~/TestTags$ global -x func1                                                                                                                              
      func1               1 DIR1/fileB.c     func1() { printf("This is function1!\n"); }  
   
   5. get absolute path of a symbol:
      gloabl -a func1

   6. find symbol which is not find in GTAGS
      
      hjiang@hjiang:~/TestTags$ global X                                                                                                                                     
      hjiang@hjiang:~/TestTags$

   7. locates the lines which have the specified pattern
      
      hjiang@hjiang:~/TestTags$ global -xg 'func'                                                                                                                            
      func                2 DIR1/fileA.c       func1();                                                                                                                      
      func                3 DIR1/fileA.c       func2();                                                                                                                      
      func                1 DIR1/fileB.c     func1() { printf("This is function1!\n"); }                                                                                     
      func                2 DIR2/fileC.c     func2(){ i++; }                                                                                                                 
      func                4 DIR2/fileC.c     func2(){ i--; }                                                                                                                 
      func                6 DIR2/fileC.c     func3()                                                                                                                         
      func                8 DIR2/fileC.c       func1();  

    8. get the path name of the specified pattern
      
      hjiang@hjiang:~/TestTags$ global -P fileA                                                                                                                              
      DIR1/fileA.c

    9. print the list of tags in a file:
     
      hjiang@hjiang:~/TestTags$ global -f DIR2/fileC.c                                                                                                                  
      func2               2 DIR2/fileC.c     func2(){ i++; }                                                                                                                 
      func2               4 DIR2/fileC.c     func2(){ i--; }                                                                                                                 
      func3               6 DIR2/fileC.c     func3()    
*** expend emacs using global
    1. gtags-find-tag 
    2. find reference of a symbol
       gtags-find-rtag
    3. find current token definition
       gtags-find-tag-froml-here
    4. find symbol witch not defined in GTAGS
       gtags-find-symbol
    5. locate a string:
       gtags-find-with-grep
*** Using gtags find definition in project
   - when ggtags-mode is enabled, use "ggtags-find-tag-dwim" 
     + if the tag at point is definition, then jump to a reference.
       if there are more than one references, list them.
     + if the tag at point is reference, then jump to the definition.
     + if the tag at point is a include header, then jump to the header.
*** Using gtags find reference in project
   using helm-gtags: helm-gtags-dwim or helm-gtags-find-rtags
   + the point is inside the function, the prompt will default to function name.
   + the point is on a function, it lists references of the function
   + if  point is on a variable, C-c g s(gtags-find-symbol) will list the varible in this buffer
*** find function that current function call
   + 
** Get the source code of a program under linux
   
** Speedbar and sr-speedbar
    Basic usage:
    + Use SPC to open the children of a node.
    + RET to open the node in another window. If node is a file, open that file; if node is a directory, enter that directory; if node is a tag in a file, jump to the location of that tag in the file.
    + U to go up parent directory.
    + n or p moves to next or previous node.
    + M-n or M-p moves to next or previous node at the current level.
    + b switches to buffer list using Speedbar presentation. You can also open children of each buffer.
    + f switches back to file list.

    sr-speedbar-toggle open sr-speedbar
* passwd
  OA and OutNet:
  Name:hjiang
  Passwd: Jiang0715039

  AST591:198.2.11.1
  AST592:198.2.156.1
  AST593:198.2.56.1
  AST594:198.2.186.1
  DEV03:172.23.1.101

  OA信息管理系统:
  User:hjiang
  Passwd:hjiang

  远程报单数据库地址: 10.112.3.249
  ezstep_jiangheng
  sa
  sa

* OpenVms
** EzEI extract 广播数据使用说明：
  0）进入 bin目录，重置环境变量
  . ./setenv 

  1）导出oc二进制数据。 -set后参数表示set号， -tp参数是主题名， -startno表示主题起始号， -endno是结束号， -fipath表示导出二进制文件路径
  ./showall -bcdt -set 109 -tp 1 -startno 1 -endno 100 -fipath ../data/output/109-1.txt

  2、使用showbcdt解析出的可视化数据,  -s为showall导出文件位置， -conf 为配置文件位置， -o为数据文件位置（可显示文件）
  ./showbcdt -bcdt -s ../data/output/109-1.txt -conf ../conf/tools/showbcdt/atp-oc-bcst.txt -o ../data/output/atp-oc.txt


  备注：
  1）目的是截取一段区间。如果是endno大于实际的数据的最大数据号的，则最终截取实际数量的。
  例如oc只有[1, 100], 则如果-startno=1， -endno=1000,实际获取的数据范围是：[1, 100]

  2) 解析可视化数据是实际数据，不包含set,type，以及序号。 但是能够保证，数据是有序递增。具体数据列表是以上oc的数据范围。


  COPY UEXE:AM63.EXE AST591"NGTS_15 SHANGHAI"::TOFF$EXE: /FTP /L
  COPY UEXE:MAHBM001.EXE AST591"NGTS_15 SHANGHAI"::TOFF$EXE: /FTP /L

** 常用查询命令:
  订单簿: mcr tol$exe:showotw -ord -set 109 -time *,*
  rdrlog: mcr tol$exe:showwp -rdr -set 109 -time *,*
  广播内存: mcr tol$exe:showwp  -brc -set 109 -p EZEI0 -tp 19 -range *,*
  订阅内存: mcr tol$exe:showall -hhbm -subinfo

** OPENVMS下DEBUG程序:
  本地主机上: set display/create/trans=tcpip/node=本地主机ip
  开发主机上: 
  COPY U3$:[ATP04.DEV.SIR.33070]MSHDPT001.C   USRC /L 
  COPY U3$:[ATP04.DEV.SIR.33070]MSHDPT002.C   USRC /L
  COPY U3$:[ATP04.DEV.SIR.33070]SHOWOTW.C     USRC /L
  COPY U3$:[ATP04.DEV.SIR.33070]MSHCCR002.C   USRC /L

  perl utools:debug.pl
  设置debug窗口的IP地址:SET DISPLAY/CREATE/TRANS=TCPIP/NODE=196.131.3.78

** 修改系统文件后CONV：
  CONV /FDL=TOFF$FDL:FTBIZSTK USER_FTBIZSTK_FILE USER_FTBIZSTK_FILE /STAT

  @BACK01$:[AIR.SCRIPT]AUTO_RESTORE.COM BACK01$:[TOFF29.DATA.POST_BACKUP.POST_BACKUP_A040400_CUR_20070312] A

** Upgrade Back Env:
     @BACK01$:[AIR.SCRIPT]AUTO_RESTORE.COM BACK01$:[TOFF20.DATA.POST_BACKUP.POST_BACKUP_20070312] A
     @BACK01$:[AIR.SCRIPT]AUTO_RESTORE.COM BACK01$:[TOFF78.DATA.POST_BACKUP.POST_BACKUP_A040600_CUR_20070312] A

** dcl脚本调试
     set verify
     define toff$verify "ON"

** openvms delete file and directory:
      a. delete a file
      delete xxx.dat;1 /l

      b. delete all files in current dir:
      delete *.*.* /l

      c. delet a dir and all files in sub dir:
      set def xxxx
      dir
      delete [...]*.*.* /tree /l

** run a openvms file with process name:

      run /detatched/process=hibertrig hibertrig
      ana/sys
      show process hibertrig

      stop hibertrig

** OpenVms Copy a Locked file:
  conv /share file new_file /stat

** 查看或在所有的虚拟桌面切换: Win + Tab
      创建新的虚拟桌面: Win + Ctrl + D
      关闭当前虚拟桌面: Win + Ctrl + F4
      切换虚拟桌面: Win + Ctrl + L/F x
      虚拟桌面顺序:
      a. 编程环境
      b. 文档编辑
      c. 文档，书籍，资料查看

** Cmder 常用命令:
      Ctrl + Tab  : Swicth Between Tabs
      Ctrl + T    : Create a New Tab

** OpenVMS 管道
      pipe install list/global | sea sys$input 85_85

      the DCL pipe command under OpenVms:

      PIPE command-sequence [separator command-sequece]

      PIPE常用功能:
      a. 多命令同时执行
      PIPE command-sequence; command-sequence; [; command-sequence]

      b. 命令执行的条件化
      PIPE command-sequence1 && command-sequence2
      PIPE command-sequence1 || command-sequence2

      c. 命令执行的管道化
      PIPE pipeline-segment | pipeline-segment [|...]

      d. Subshell excution
      PIPE ( command-sequence [ separator command-sequence]...)

      e. Background excution
      PIPE command-sequence [ separator command-sequence]... &

** DWR脚本编译:

      BACK01$:[PATCH.DWRTOOL.DWR.DWR_JH]
      $ SET DEF BACK01$:[PATCH.DWRTOOL]
      @[.TOOLSET]DWR_SETENV JH
      DWR$LOAD
      perl dwrtool.pl -c DEBUG.CONF -l JH -n JH
      DWR$EXTRACT
      DWR$QUIT

      perl private_tools\ATP\AIR_FEEDER_BECMD.PL AST591 "perl TOL$DCL:BIZTOOL.PL -m TR0000400023590000" " : [TRYYYYYYYYYYYYYYYY0000400023590000]" search

** 常用主机IP地址:
      dev03 : 172.23.1.101

** 开发主机上代码作QA检查
      @dtools:check_qa xxxx.c SIR [ADD|REPLACE|...]

** 竟价模拟器:
      http://svn.tc.com/TOOLDoc/TestTools/MTPEMulator/MTPEmulator文档.docx
      U3$:[RXCHEN.DEV.SRC]TEST_SIM.C;59
** trunc
      set def data02$:[000000]
      set file /trunc [...]*.*
** Openvms条件编译:
      comp xxxx /define=TEST
      is same as:
      #define TEST 1

      /DEFINE="funct(a)=a+sin(a)"
      This definition produces the same results as the following definition:
      #define funct(a) a+sin(a)

      gcc条件编译:
      gcc xxxx.c -D TRUE
      is same as use this macro in xxxx.c

      #define TRUE 1

      mcr NGTS_SYS$:[TOFF55.TOOLS.EXE_I64]XDATA.EXE AGP101$:[TOFF55.DATA.FILES]FPSERI20106.RUJ  toff$fdl:RMSERI2T.FED toff$work_Dir:hjiang_ser2.csv
** 后台环境主机确认
   SEA USER_FTOP_MSG_FILE "MASTER HRRM"
   显示:
   [INFORMATION] HRRM on Host(XXXX) is the Master HRRM 
* Atp Frame Test
** upgrade to latest atp version
   @BACK01$:[TOFF15.DATA.POST_BACKUP]POST_RESTORE_CNTRL.COM
   BACK01$:[TOFF27.DATA.POST_BACKUP.POST_BACKUP_A050000_AST_20070312]
** front end order sending (iterate)
   file:/d/Org/Atp/FrameTest/allatp.sql
** set 100 test
| set | order book size | order number(when switch) | pbu status (Normal/Abnormal) | order resp(Normal/Abnormal) | v_log  | front and back diff(Same/Diff) |
|-----+-----------------+---------------------------+------------------------------+-----------------------------+--------+--------------------------------|
| 100 |         1000000 |                    521534 | Normal                       | Normal                      | NO_ERR | Same                           |
| 101 |          400000 |                           |                              |                             |        |                                |
| 102 |                 |                           |                              |                             |        |                                |
| 104 |                 |                           |                              |                             |        |                                |
| 105 |                 |                           |                              |                             |        |                                |
| 106 |                 |                           |                              |                             |        |                                |
| 109 |                 |                           |                              |                             |        |                                |

* Core PlatFrom Auto Run:
** SVN
   http://svn.tc.com/MultiGroupTask///trunk/
** Upgrade
   cd /cygdrive/y/DevRelease/ATP_AUTO_INTEG/A050000  
   tel 198.1.153.1
   set def BACK01$:[PATCH.15.A050000_AC_PATCH]
   @BACK01$:[AIR.SCRIPT]AUTO_RESTORE.COM BACK01$:[TOFF55.DATA.POST_BACKUP.POST_BACKUP_A040700_CUR_20070312] "" temp01$:[testenv_Data.atp.dst]DST_ENV_CFG.BCK

   ./AtpCode/DDCL/POST_RESTORE_CNTRL.COM:1736:         " PLEASE ENTER THE USER FOR THE CS:[DEFAULT ''TCG_USR_CS_NET']"
   ./AtpCode/DDCL/POST_RESTORE_CNTRL.COM:1741:         " PLEASE ENTER THE PASSWORD FOR THE CS:[USER ''TCG_USR_CS_NET_TMP']"
   
   ./AtpCode/DDCL/TOFF_ONLINE_MANAGEMENT.COM:113:$ ASK_FOR_TC_PWD = """''SHIFT'PLEASE ENTER ''TCG_USR_HD_ADM' PASSWORD ON TC: """
   ./AtpCode/DDCL/TOFF_ONLINE_MANAGEMENT.COM:140:$ ASK_FOR_CS_PWD = """''SHIFT'PLEASE ENTER ''TCG_USR_CS_ADM' PASSWORD ON CS: """
   ./AtpCode/DDCL/TOFF_ONLINE_MANAGEMENT.COM:164:$ ASK_FOR_EI_PWD = """''SHIFT'PLEASE ENTER ''TCG_USR_EI_ADM' PASSWORD ON EI: """

   Q1: cscheck 若填201(不是0201), 结点范围检查错误

   bashftp ./PATCH_DATA.COM BACK01$:[PATCH.15.A050000_AC_PATCH] u
   bashftp ./GEN_PATCH_SCRIPT.PL BACK01$:[PATCH.15.A050000_AC_PATCH] u
   bashftp ./UPGRADE_VMS.COM BACK01$:[PATCH.15.A050000_AC_PATCH] u
  
   COPY [.GENERIC.15]FPENVCONF_AC.DAT 198.1.40.1"NOP_15 SHANGHAI"::TOFF$:[TOFF15.DATA.FILES]FPENVCONF.DAT /FTP /L
   COPY [.GENERIC.15]FPENVCONF_AC.DAT 198.1.46.1"NOP_15 SHANGHAI"::TOFF$:[TOFF15.DATA.FILES]FPENVCONF.DAT /FTP /L

   @BACK01$:[TOFF15.DATA.POST_BACKUP]POST_RESTORE_CNTRL.COM

   %PURGE-W-SEARCHFAIL, error searching for DSA0:[TOFF15.SYSTEM.EXE]*.EXE;*
   -RMS-E-FNF, file not found
   %PURGE-W-SEARCHFAIL, error searching for DSA0:[TOFF_NET15.DCL]*.COM;*
   -RMS-E-FNF, file not found
* ToDoList
** <2018-07-17 ÖÜ¶þ>                                               :20180717:
*** DONE [#B] learn emacs org and make a todo list                      :org:
*** DONE [#A] get the feeling of the offline of EI               :ei:offline:
*** TODO [#C] programming pearl, ch2 algorithm                    :algorithm:
*** code submit:
    [[file:code_submit.org][code_submit]]

** <2018-07-18 ÖÜÈý>
** <2018-07-20 ÖÜÎå>
** <2018-07-23 ÖÜÒ»>
